import manifest from "./gallery-manifest.json";

/**
 * Typed access to the painting manifest generated by
 * `scripts/import-paintings.mjs` from the photos in `paintings/`.
 *
 * Consumed by the Gallery page (all works), the portfolio home (a featured
 * few), and the demo shop catalog (placeholder products). Titles in the
 * manifest are placeholders — Anna renames them (see docs/HANDOVER.md).
 */
export type GalleryItem = {
  slug: string;
  title: string;
  source: string;
  large: string;
  largeJpg: string;
  thumb: string;
  thumbJpg: string;
  width: number | null;
  height: number | null;
  accentHex: string;
};

const items = manifest as GalleryItem[];

/** All paintings, in manifest order. */
export function getGalleryItems(): GalleryItem[] {
  return items;
}

/** A single painting by slug, or null. */
export function getGalleryItem(slug: string): GalleryItem | null {
  return items.find((i) => i.slug === slug) ?? null;
}

/** The first `n` paintings — used for the "selected work" strip on the home. */
export function getFeatured(n: number): GalleryItem[] {
  return items.slice(0, n);
}
